### ISSUE TITLE
Dot e comma in una colonna testo contenente numeri

### ISSUE THREAD

**Issue by paolovolterra** [ondata/guidaVisiData#14]
Ciao
prendiamo un csv che contiene colonne con numeri esposti non in formato machine readable: i numeri infatti hanno il separatore delle migliaia!
1) Come si fa a togliere i punti?
2) i decimali sono esposti dopo la virgola. Se voglio trasformare la virola in un punto in modo da importarli più agevolmente in Python?
Ciao a tutti
p

**Comment by aborruso** [comment]
Ciao @paolovolterra una sezione della guida si chiama [Trasformare una colonna tramite espressione regolare (trova e sostituisci)](https://github.com/ondata/guidaVisiData/blob/master/testo/README.md#trasformare-una-colonna-tramite-espressione-regolare-trova-e-sostituisci)

Puoi seguire quella. Qui lo vedi in azione http://youtu.be/zn_d03eX8kA?hd=1

**Comment by anjakefala** [comment]
...Is this it? :angel: @aborruso

**Comment by aborruso** [comment]
@anjakefala yes :)

**Comment by anjakefala** [comment]
Hi @paolovolterra  and @aborruso ! There should now be a method implemented on the develop branch. It will be part of the next release.

You will need to set your shell environment variable LC_NUMERIC to a locale which interprets commas as decimals. Any European one should do. I tested this with en_DK.UTF-8.

Then, type the column with type-floatlocale. You can execute the longname by pressing Space, and then typing out type-floatlocale. I would bind the command to a keystroke, if you use it frequently. The documentation for that in "How to configure commands" here: https://www.visidata.org/docs/customize/

If you want to replace the currentl type-float with type-floatlocale, add to your ~/.visidatarc:

unbindkey('%')
bindkey('%', 'type-floatlocale')

or if you never use type-floatsi, you can do

unbindkey('z%')
bindkey('z%', 'type-floatlocale')

that is the gist!

Thanks for making this feature request!

**Comment by paolovolterra** [comment]
non sono un tecnico e sto cercando di capire come funziona github
ho dimenticato di dire (fare?) qualcosa per concludere questa issue
scusate

**Comment by aborruso** [comment]
@paolovolterra una cosa semplice, che non è tecnica: fare sapere se dopo che hai letto la risposta, ha risolto.
