### ISSUE TITLE
Sostituzione di valori

### ISSUE THREAD

**Issue by paolovolterra** [ondata/guidaVisiData#15]
Ariciao
Come si sostituiscono i valori delle celle di alcune colonne?
Voglio ad es.: cambiare tutti i "Pippo" in "Paperino"

Ciao a tutti e grazie
p

**Comment by aborruso** [comment]
Ciao @paolovolterra nella guida c'è una sezione denominata [Fare un trova e sostituisci globale](https://github.com/ondata/guidaVisiData/blob/master/testo/README.md#fare-un-trova-e-sostituisci-globale).

Basta seguire quei passi. Qui un esempio http://youtu.be/uQttBd7GpMs?hd=1

**Comment by anjakefala** [comment]
Hi @paolomainardi and @aborruso ! There should now be a method implemented on the develop branch. It will be part of the next release.

You will need to set your shell environment variable LC_NUMERIC to a locale which interprets commas as decimals. Any European one should do. I tested this with en_DK.UTF-8.

Then, type the column with type-floatlocale. You can execute the longname by pressing Space, and then typing out type-floatlocale. I would bind the command to a keystroke, if you use it frequently. The documentation for that in "How to configure commands" here: https://www.visidata.org/docs/customize/

If you want to replace the currentl type-float with type-floatlocale, add to your ~/.visidatarc:

unbindkey('%')
bindkey('%', 'type-floatlocale')

or if you never use type-floatsi, you can do

unbindkey('z%')
bindkey('z%', 'type-floatlocale')

that is the gist!

Thanks for making this feature request!

**Comment by aborruso** [comment]
Hi @anjakefala in this issue we talk about global search & replace: to find globally "foo" and replace it with "moo".

It's not a locale floating point symbol matter ;)

**Comment by anjakefala** [comment]
Oh, I am sorry! I saw 'colonne' and thought this would be the one :sweat_smile: . I remember seeing an issue somewhere here about comma floats!

**Comment by paolovolterra** [comment]
non sono un tecnico e sto cercando di capire come funziona github
ho dimenticato di dire (fare?) qualcosa per concludere questa issue
scusate

**Comment by aborruso** [comment]
@paolovolterra una cosa semplice, che non è tecnica: fare sapere se dopo che hai letto la risposta, ha risolto.
