### ISSUE TITLE
setting tabella provocano non leggibilità del testo in modalità scura

### ISSUE THREAD

**Issue by UO-TransizioneDigitaleComunePalermo** [ondata/guidaVisiData#48]
![image](https://user-images.githubusercontent.com/42996217/143992694-c21bc5fb-f893-446b-a19b-eeb88a9e0c2b.png)

nella modalità scura
i seguenti setting della tabella nel file `style.css`
```
/* colore righe pari */
tr:nth-child(even) {
  background-color: #f2f2f2;
}
```
provocano una non leggibilità del testo delle righe in fase alterna

**Comment by aborruso** [comment]
![image](https://user-images.githubusercontent.com/30607/148700941-9c473074-809d-4944-ad2b-9288fdd908bc.png)
