### ISSUE TITLE
Spostare righe combinazione tasti

### ISSUE THREAD

**Issue by gbvitrano** [ondata/guidaVisiData#6]
Buongiono :-)
sto studiando la [guida -spostare-righe ](https://github.com/ondata/guidaVisiData/blob/master/testo/README.md#spostare-righe ) usando la cobinazione di stati indicata mi sparice tutto 
**Shift-j** per spostare la riga corrente verso il basso;
**Shift-k** per spostare la riga corrente verso l'alto.

se invece uso **Shift+j** o **Shift+k**  le righe vengono spostate

**Comment by aborruso** [comment]
Caro @gbvitrano è indicato male: il `-` è per dire `SHIFT`, combinato con `j`.

Ma non è uniforme con il resto e si capisce male.

Lo modifico, grazie

**Comment by aborruso** [comment]
@all-contributors please add @gbvitrano  for content, example
